name: Build and Push Docker Image

on:
  push:
    branches:
      - test/1
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - run: ls -la
      - name: Build Docker Image
        run: |
          docker build -t testimage:v1 -f test.dockerfile .

      - name: Tag latest and Push
        run: |
          docker tag testimage:v1 singasaiprasad/testimage:v1
          docker push singasaiprasad/testimage:v1